services:
  vault:
    image: hashicorp/vault:1.6.2
    container_name: vault-dev
    ports:
      - "8200:8200"
    environment:
      - VAULT_LOCAL_CONFIG={"storage":{"file":{"path":"/vault/file"}},"listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":1}},"ui":true,"disable_mlock":true,"telemetry":{"prometheus_retention_time":"10m","disable_hostname":true}}
    command: server
    volumes:
      - vault-data:/vault/file
    cap_add:
      - IPC_LOCK
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"
    networks:
      - vault-net

  vault-seed:
    build:
      context: ./vault
      dockerfile: Dockerfile
    container_name: vault-seed
    environment:
      - VAULT_ADDR=http://vault-dev:8200
      - VAULT_TOKEN=myroot
    depends_on:
      - vault
    networks:
      - vault-net
    volumes:
      - vault-data:/vault/file
    # Контейнер завершится после загрузки данных
    restart: "no"

  vault-seed-acl:
    build:
      context: ./vault
      dockerfile: Dockerfile
    container_name: vault-seed-acl
    environment:
      - VAULT_ADDR=http://vault-dev:8200
      - VAULT_TOKEN=myroot
    depends_on:
      - vault
      - vault-seed
    networks:
      - vault-net
    volumes:
      - vault-data:/vault/file
    command: ["python", "seed_acl.py"]
    # Контейнер завершится после загрузки ACL Policies
    restart: "no"

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: keycloak
    ports:
      - "9080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=9080
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
    networks:
      - vault-net

  vault-seed-oidc:
    build:
      context: ./vault
      dockerfile: Dockerfile
    container_name: vault-seed-oidc
    environment:
      - VAULT_ADDR=http://vault-dev:8200
      - VAULT_TOKEN=myroot
      - KEYCLOAK_URL=http://keycloak:8080
    depends_on:
      - vault
      - keycloak
    networks:
      - vault-net
    volumes:
      - vault-data:/vault/file
    command: ["python", "seed_oidc.py"]
    restart: "no"

  vault-load-tester:
    build:
      context: ./vault
      dockerfile: Dockerfile
    container_name: vault-load-tester
    environment:
      - VAULT_ADDR=http://vault-dev:8200
      - VAULT_TOKEN=myroot
    depends_on:
      - vault
      - vault-seed
    networks:
      - vault-net
    command: ["python", "load_tester.py"]
    # Бесконечный рестарт, пока мы руками не остановим стенд
    restart: "unless-stopped"

  vault-constant-load:
    build:
      context: ./vault
      dockerfile: Dockerfile
    container_name: vault-constant-load
    environment:
      - VAULT_ADDR=http://vault-dev:8200
      - VAULT_TOKEN=myroot
      - TARGET_RPS=1000
      - WORKERS=50
    depends_on:
      - vault
      - vault-seed
    networks:
      - vault-net
    command: ["python", "constant_load.py"]
    restart: "unless-stopped"


networks:
  vault-net:
    name: vault-net
    driver: bridge

volumes:
  vault-data:
